package tn.esprit.pi.controller.aichatbot;

import java.util.List;

import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import tn.esprit.pi.dto.aichatbot.ChatMessageCreateRequest;
import tn.esprit.pi.dto.aichatbot.ChatMessageResponse;
import tn.esprit.pi.enums.aichatbot.MessageType;
import tn.esprit.pi.enums.aichatbot.SenderType;
import tn.esprit.pi.service.aichatbot.ChatMessageService;

@RestController
@RequestMapping("/api/ai/chat-messages")
@RequiredArgsConstructor
@Tag(name = "AI Chat Messages", description = """
        APIs for managing messages within AI chat sessions.

        This controller handles the exchange of messages between patients and the AI
        assistant. Each message contains the conversation content along with metadata
        about the sender and message type.

        ## Message Features
        - **Two-way Communication**: Supports messages from both PATIENT and AI
        - **Message Types**: Different types including TEXT, IMAGE, etc.
        - **Timestamps**: Each message is timestamped for conversation flow
        - **Context Awareness**: Messages are linked to sessions for context

        ## Message Types
        - **TEXT**: Standard text-based messages
        - **IMAGE**: Image attachments (future feature)
        - **SYSTEM**: System-generated messages (welcome, warnings)

        ## Sender Types
        - **PATIENT**: Messages sent by the patient user
        - **AI**: Responses generated by the Groq AI system

        ## Message Flow
        1. Patient sends a message (PATIENT sender, TEXT type)
        2. System processes the message and updates context
        3. AI generates a response based on context
        4. System sends AI response (AI sender, TEXT type)
        5. Conversation continues until session ends

        ## Context Building
        The AI uses accumulated conversation context to provide personalized
        responses. Key context elements include:
        - Previous questions and answers
        - Patient's medical history (if shared)
        - Current symptoms or concerns
        - Medication information
        """)
@SecurityRequirement(name = "Bearer Authentication")
public class ChatMessageController {

    private final ChatMessageService chatMessageService;

    @Operation(
            summary = "Get Messages by Session",
            description = """
                    Retrieves all messages for a specific chat session.

                    This endpoint returns the complete conversation history for a session,
                    ordered chronologically (oldest first).

                    ## Path Parameters
                    - sessionId: The unique identifier of the chat session

                    ## Response Details
                    - Returns list of all messages in the session
                    - Each message includes content, sender, timestamp
                    - Messages are ordered by creation time
                    """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Messages retrieved successfully.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "401", description = "Unauthorized. Invalid or missing authentication token.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "404", description = "Chat session not found.",
                    content = @Content(mediaType = "application/json"))
    })
    @GetMapping("/session/{sessionId}")
    public ResponseEntity<List<ChatMessageResponse>> findBySessionId(
            @Parameter(description = "The unique identifier of the chat session", required = true)
            @PathVariable Long sessionId) {
        return ResponseEntity.ok(chatMessageService.toResponseList(chatMessageService.findBySessionId(sessionId)));
    }

    @Operation(
            summary = "Get Messages by Session and Sender",
            description = """
                    Retrieves messages filtered by both session and sender type.

                    This endpoint is useful for retrieving only patient messages or
                    only AI responses within a session.

                    ## Path Parameters
                    - sessionId: The unique identifier of the chat session
                    - senderType: The sender type to filter by (PATIENT or AI)

                    ## Use Cases
                    - Get only patient questions for review
                    - Get only AI responses for analysis
                    - Separate user input from AI responses

                    ## Response Details
                    - Returns filtered list of messages
                    """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Messages retrieved successfully.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "401", description = "Unauthorized. Invalid or missing authentication token.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "404", description = "Chat session not found.",
                    content = @Content(mediaType = "application/json"))
    })
    @GetMapping("/session/{sessionId}/sender/{senderType}")
    public ResponseEntity<List<ChatMessageResponse>> findBySessionIdAndSenderType(
            @Parameter(description = "The unique identifier of the chat session", required = true)
            @PathVariable Long sessionId,
            @Parameter(description = "The sender type to filter by", required = true,
                    schema = @Schema(allowableValues = {"PATIENT", "AI"}))
            @PathVariable SenderType senderType) {
        return ResponseEntity.ok(chatMessageService.toResponseList(chatMessageService.findBySessionIdAndSenderType(sessionId, senderType)));
    }

    @Operation(
            summary = "Get Messages by Session and Type",
            description = """
                    Retrieves messages filtered by both session and message type.

                    This endpoint filters messages by type within a session.

                    ## Path Parameters
                    - sessionId: The unique identifier of the chat session
                    - messageType: The message type to filter by (TEXT, IMAGE, SYSTEM)

                    ## Response Details
                    - Returns filtered list of messages
                    """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Messages retrieved successfully.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "401", description = "Unauthorized. Invalid or missing authentication token.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "404", description = "Chat session not found.",
                    content = @Content(mediaType = "application/json"))
    })
    @GetMapping("/session/{sessionId}/type/{messageType}")
    public ResponseEntity<List<ChatMessageResponse>> findBySessionIdAndMessageType(
            @Parameter(description = "The unique identifier of the chat session", required = true)
            @PathVariable Long sessionId,
            @Parameter(description = "The message type to filter by", required = true,
                    schema = @Schema(allowableValues = {"TEXT", "IMAGE", "SYSTEM"}))
            @PathVariable MessageType messageType) {
        return ResponseEntity.ok(chatMessageService.toResponseList(chatMessageService.findBySessionIdAndMessageType(sessionId, messageType)));
    }

    @Operation(
            summary = "Send a Message",
            description = """
                    Sends a new message in an existing chat session.

                    This endpoint handles both patient messages and AI responses.
                    When a patient message is received, it triggers AI response generation.

                    ## Request Details
                    - sessionId: The chat session this message belongs to
                    - content: The message text content
                    - senderType: Who is sending the message (PATIENT or AI)
                    - messageType: Type of message (TEXT, IMAGE, SYSTEM)

                    ## Message Processing
                    For PATIENT messages:
                    1. Message is saved to the database
                    2. Session context is updated with new information
                    3. AI is invoked to generate a response
                    4. AI response is saved and returned

                    For AI messages:
                    1. Message is saved as-is (typically from AI processing)

                    ## Response Details
                    - Returns the created message
                    - For patient messages, may include AI response
                    """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "201", description = "Message created successfully.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "401", description = "Unauthorized. Invalid or missing authentication token.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "404", description = "Chat session not found.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "400", description = "Invalid message data or session not active.",
                    content = @Content(mediaType = "application/json"))
    })
    @PostMapping
    public ResponseEntity<ChatMessageResponse> create(@Valid @RequestBody ChatMessageCreateRequest request) {
        return ResponseEntity.status(HttpStatus.CREATED).body(chatMessageService.create(request));
    }

    @Operation(
            summary = "Soft Delete Message",
            description = """
                    Soft deletes a message by setting its deletedAt timestamp.

                    This endpoint performs a soft delete on a message, removing it
                    from active views while preserving it in the database.

                    ## Path Parameters
                    - id: The unique identifier of the message to delete

                    ## Effects
                    - Message is marked as deleted
                    - Message is hidden from conversation views
                    - Context is updated accordingly
                    - Original message data is preserved

                    ## Response Details
                    - Returns 204 No Content on success
                    """)
    @ApiResponses(value = {
            @ApiResponse(responseCode = "204", description = "Message soft deleted successfully.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "401", description = "Unauthorized. Invalid or missing authentication token.",
                    content = @Content(mediaType = "application/json")),
            @ApiResponse(responseCode = "404", description = "Message not found.",
                    content = @Content(mediaType = "application/json"))
    })
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> softDelete(
            @Parameter(description = "The unique identifier of the message to delete", required = true)
            @PathVariable Long id) {
        chatMessageService.softDelete(id);
        return ResponseEntity.noContent().build();
    }
}
