package tn.esprit.pi.enums.vital;

public enum VitalType {
    TEMPERATURE, HEART_RATE,
    BLOOD_PRESSURE_SYSTOLIC, BLOOD_PRESSURE_DIASTOLIC,
    OXYGEN_SATURATION, RESPIRATORY_RATE, BLOOD_GLUCOSE
}
