import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { TableModule } from 'primeng/table';
import { AvatarModule } from 'primeng/avatar';
import { ChartModule } from 'primeng/chart';

@Component({
  selector: 'app-admin-dashboard',
  imports: [CommonModule, TableModule, AvatarModule, ChartModule],
  templateUrl: './dashboard.component.html',
  styleUrl: './dashboard.component.scss',
})
export class AdminDashboardComponent {
  view: 'table' | 'chart' = 'table';

  users = [
    {
      id: 1,
      name: 'Omar Bouchoucha',
      email: 'omar@example.com',
      initials: 'OB',
      role: 'Admin',
      status: 'Active',
      joined: '2024-01-10',
    },
    {
      id: 2,
      name: 'Sara Malik',
      email: 'sara@example.com',
      initials: 'SM',
      role: 'Editor',
      status: 'Active',
      joined: '2024-01-15',
    },
    {
      id: 3,
      name: 'James Carter',
      email: 'james@example.com',
      initials: 'JC',
      role: 'Viewer',
      status: 'Inactive',
      joined: '2024-02-03',
    },
    {
      id: 4,
      name: 'Lena Fischer',
      email: 'lena@example.com',
      initials: 'LF',
      role: 'Editor',
      status: 'Pending',
      joined: '2024-02-20',
    },
    {
      id: 5,
      name: 'Karim Nassar',
      email: 'karim@example.com',
      initials: 'KN',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-03-05',
    },
    {
      id: 6,
      name: 'Aisha Diallo',
      email: 'aisha@example.com',
      initials: 'AD',
      role: 'Admin',
      status: 'Active',
      joined: '2024-03-12',
    },
    {
      id: 7,
      name: 'Tom Weber',
      email: 'tom@example.com',
      initials: 'TW',
      role: 'Viewer',
      status: 'Inactive',
      joined: '2024-03-18',
    },
    {
      id: 8,
      name: 'Maria Garcia',
      email: 'maria@example.com',
      initials: 'MG',
      role: 'Editor',
      status: 'Active',
      joined: '2024-04-01',
    },
    {
      id: 9,
      name: 'John Smith',
      email: 'john@example.com',
      initials: 'JS',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-04-10',
    },
    {
      id: 10,
      name: 'Anna Schmidt',
      email: 'anna@example.com',
      initials: 'AS',
      role: 'Editor',
      status: 'Pending',
      joined: '2024-04-22',
    },
    {
      id: 11,
      name: 'David Lee',
      email: 'david@example.com',
      initials: 'DL',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-05-05',
    },
    {
      id: 12,
      name: 'Sophie Brown',
      email: 'sophie@example.com',
      initials: 'SB',
      role: 'Viewer',
      status: 'Inactive',
      joined: '2024-05-14',
    },
    {
      id: 13,
      name: 'Michael Chen',
      email: 'michael@example.com',
      initials: 'MC',
      role: 'Admin',
      status: 'Active',
      joined: '2024-05-20',
    },
    {
      id: 14,
      name: 'Emma Wilson',
      email: 'emma@example.com',
      initials: 'EW',
      role: 'Editor',
      status: 'Active',
      joined: '2024-06-01',
    },
    {
      id: 15,
      name: 'Robert Taylor',
      email: 'robert@example.com',
      initials: 'RT',
      role: 'Viewer',
      status: 'Pending',
      joined: '2024-06-10',
    },
    {
      id: 16,
      name: 'Lisa Anderson',
      email: 'lisa@example.com',
      initials: 'LA',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-06-15',
    },
    {
      id: 17,
      name: 'Chris Martin',
      email: 'chris@example.com',
      initials: 'CM',
      role: 'Editor',
      status: 'Inactive',
      joined: '2024-07-02',
    },
    {
      id: 18,
      name: 'Rachel Green',
      email: 'rachel@example.com',
      initials: 'RG',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-07-12',
    },
    {
      id: 19,
      name: 'Daniel White',
      email: 'daniel@example.com',
      initials: 'DW',
      role: 'Editor',
      status: 'Active',
      joined: '2024-07-20',
    },
    {
      id: 20,
      name: 'Jennifer Davis',
      email: 'jennifer@example.com',
      initials: 'JD',
      role: 'Viewer',
      status: 'Pending',
      joined: '2024-08-01',
    },
    {
      id: 21,
      name: 'Alex Johnson',
      email: 'alex@example.com',
      initials: 'AJ',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-08-05',
    },
    {
      id: 22,
      name: 'Emily Roberts',
      email: 'emily@example.com',
      initials: 'ER',
      role: 'Editor',
      status: 'Active',
      joined: '2024-08-10',
    },
    {
      id: 23,
      name: 'Mark Thompson',
      email: 'mark@example.com',
      initials: 'MT',
      role: 'Viewer',
      status: 'Inactive',
      joined: '2024-08-15',
    },
    {
      id: 24,
      name: 'Sarah Miller',
      email: 'sarah@example.com',
      initials: 'SM2',
      role: 'Admin',
      status: 'Active',
      joined: '2024-08-20',
    },
    {
      id: 25,
      name: 'Kevin Harris',
      email: 'kevin@example.com',
      initials: 'KH',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-09-01',
    },
    {
      id: 26,
      name: 'Laura Clark',
      email: 'laura@example.com',
      initials: 'LC',
      role: 'Editor',
      status: 'Pending',
      joined: '2024-09-05',
    },
    {
      id: 27,
      name: 'Brian Lewis',
      email: 'brian@example.com',
      initials: 'BL',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-09-10',
    },
    {
      id: 28,
      name: 'Nicole Walker',
      email: 'nicole@example.com',
      initials: 'NW',
      role: 'Editor',
      status: 'Active',
      joined: '2024-09-15',
    },
    {
      id: 29,
      name: 'Steven Hall',
      email: 'steven@example.com',
      initials: 'SH',
      role: 'Viewer',
      status: 'Inactive',
      joined: '2024-09-20',
    },
    {
      id: 30,
      name: 'Ashley Young',
      email: 'ashley@example.com',
      initials: 'AY',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-10-01',
    },
    {
      id: 31,
      name: 'Patrick King',
      email: 'patrick@example.com',
      initials: 'PK',
      role: 'Editor',
      status: 'Active',
      joined: '2024-10-05',
    },
    {
      id: 32,
      name: 'Megan Wright',
      email: 'megan@example.com',
      initials: 'MW',
      role: 'Viewer',
      status: 'Pending',
      joined: '2024-10-10',
    },
    {
      id: 33,
      name: 'Timothy Scott',
      email: 'timothy@example.com',
      initials: 'TS',
      role: 'Admin',
      status: 'Active',
      joined: '2024-10-15',
    },
    {
      id: 34,
      name: 'Kimberly Green',
      email: 'kimberly@example.com',
      initials: 'KG',
      role: 'Editor',
      status: 'Active',
      joined: '2024-10-20',
    },
    {
      id: 35,
      name: 'Andrew Baker',
      email: 'andrew@example.com',
      initials: 'AB',
      role: 'Viewer',
      status: 'Inactive',
      joined: '2024-11-01',
    },
    {
      id: 36,
      name: 'Brittany Adams',
      email: 'brittany@example.com',
      initials: 'BA',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-11-05',
    },
    {
      id: 37,
      name: 'Jason Nelson',
      email: 'jason@example.com',
      initials: 'JN',
      role: 'Editor',
      status: 'Active',
      joined: '2024-11-10',
    },
    {
      id: 38,
      name: 'Amanda Carter',
      email: 'amanda@example.com',
      initials: 'AC',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-11-15',
    },
    {
      id: 39,
      name: 'Ryan Mitchell',
      email: 'ryan@example.com',
      initials: 'RM',
      role: 'Viewer',
      status: 'Pending',
      joined: '2024-11-20',
    },
    {
      id: 40,
      name: 'Stephanie Perez',
      email: 'stephanie@example.com',
      initials: 'SP',
      role: 'Editor',
      status: 'Active',
      joined: '2024-12-01',
    },
    {
      id: 41,
      name: 'Brandon Roberts',
      email: 'brandon@example.com',
      initials: 'BR',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-12-05',
    },
    {
      id: 42,
      name: 'Heather Turner',
      email: 'heather@example.com',
      initials: 'HT',
      role: 'Editor',
      status: 'Inactive',
      joined: '2024-12-10',
    },
    {
      id: 43,
      name: 'Justin Phillips',
      email: 'justin@example.com',
      initials: 'JP',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-12-15',
    },
    {
      id: 44,
      name: 'Christina Campbell',
      email: 'christina@example.com',
      initials: 'CC',
      role: 'Viewer',
      status: 'Active',
      joined: '2024-12-20',
    },
    {
      id: 45,
      name: 'Joshua Parker',
      email: 'joshua@example.com',
      initials: 'JP2',
      role: 'Editor',
      status: 'Pending',
      joined: '2025-01-01',
    },
    {
      id: 46,
      name: 'Rebecca Evans',
      email: 'rebecca@example.com',
      initials: 'RE',
      role: 'Admin',
      status: 'Active',
      joined: '2025-01-05',
    },
    {
      id: 47,
      name: 'Tyler Edwards',
      email: 'tyler@example.com',
      initializer: 'TE',
      role: 'Viewer',
      status: 'Active',
      joined: '2025-01-10',
    },
    {
      id: 48,
      name: 'Samantha Collins',
      email: 'samantha@example.com',
      initials: 'SC',
      role: 'Editor',
      status: 'Active',
      joined: '2025-01-15',
    },
    {
      id: 49,
      name: 'Aaron Stewart',
      email: 'aaron@example.com',
      initializer: 'AS2',
      role: 'Viewer',
      status: 'Inactive',
      joined: '2025-01-20',
    },
    {
      id: 50,
      name: 'Vanessa Sanchez',
      email: 'vanessa@example.com',
      initials: 'VS',
      role: 'Viewer',
      status: 'Active',
      joined: '2025-02-01',
    },
    {
      id: 51,
      name: 'Jonathan Morris',
      email: 'jonathan@example.com',
      initials: 'JM',
      role: 'Editor',
      status: 'Active',
      joined: '2025-02-05',
    },
    {
      id: 52,
      name: 'Olivia Rogers',
      email: 'olivia@example.com',
      initials: 'OR',
      role: 'Viewer',
      status: 'Active',
      joined: '2025-02-10',
    },
    {
      id: 53,
      name: 'Jacob Reed',
      email: 'jacob@example.com',
      initials: 'JR',
      role: 'Viewer',
      status: 'Pending',
      joined: '2025-02-15',
    },
    {
      id: 54,
      name: 'Hannah Cook',
      email: 'hannah@example.com',
      initials: 'HC',
      role: 'Editor',
      status: 'Active',
      joined: '2025-02-20',
    },
    {
      id: 55,
      name: 'Ethan Morgan',
      email: 'ethan@example.com',
      initializer: 'EM',
      role: 'Viewer',
      status: 'Active',
      joined: '2025-03-01',
    },
    {
      id: 56,
      name: 'Madison Bell',
      email: 'madison@example.com',
      initials: 'MB',
      role: 'Admin',
      status: 'Active',
      joined: '2025-03-05',
    },
    {
      id: 57,
      name: 'Nathan Murphy',
      email: 'nathan@example.com',
      initials: 'NM',
      role: 'Viewer',
      status: 'Inactive',
      joined: '2025-03-10',
    },
    {
      id: 58,
      name: 'Abigail Bailey',
      email: 'abigail@example.com',
      initials: 'AB2',
      role: 'Editor',
      status: 'Active',
      joined: '2025-03-15',
    },
    {
      id: 59,
      name: 'Jacob Rivera',
      email: 'jacob2@example.com',
      initializer: 'JR2',
      role: 'Viewer',
      status: 'Active',
      joined: '2025-03-20',
    },
    {
      id: 60,
      name: 'Elizabeth Cooper',
      email: 'elizabeth@example.com',
      initials: 'EC',
      role: 'Editor',
      status: 'Pending',
      joined: '2025-04-01',
    },
    {
      id: 61,
      name: 'Christopher Richardson',
      email: 'chris2@example.com',
      initials: 'CR',
      role: 'Viewer',
      status: 'Active',
      joined: '2025-04-05',
    },
    {
      id: 62,
      name: 'Ava Cox',
      email: 'ava@example.com',
      initials: 'AC2',
      role: 'Viewer',
      status: 'Active',
      joined: '2025-04-10',
    },
    {
      id: 63,
      name: 'Isaiah Howard',
      email: 'isaiah@example.com',
      initials: 'IH',
      role: 'Editor',
      status: 'Active',
      joined: '2025-04-15',
    },
    {
      id: 64,
      name: 'Victoria Ward',
      email: 'victoria@example.com',
      initials: 'VW',
      role: 'Viewer',
      status: 'Inactive',
      joined: '2025-04-20',
    },
    {
      id: 65,
      name: 'Connor Torres',
      email: 'connor@example.com',
      initials: 'CT',
      role: 'Viewer',
      status: 'Active',
      joined: '2025-05-01',
    },
    {
      id: 66,
      name: 'Grace Peterson',
      email: 'grace@example.com',
      initials: 'GP',
      role: 'Editor',
      status: 'Active',
      joined: '2025-05-05',
    },
    {
      id: 67,
      name: 'Liam Gray',
      email: 'liam@example.com',
      initials: 'LG',
      role: 'Viewer',
      status: 'Pending',
      joined: '2025-05-10',
    },
    {
      id: 68,
      name: 'Chloe Ramirez',
      email: 'chloe@example.com',
      initials: 'CR2',
      role: 'Viewer',
      status: 'Active',
      joined: '2025-05-15',
    },
    {
      id: 69,
      name: 'Henry James',
      email: 'henry@example.com',
      initials: 'HJ',
      role: 'Editor',
      status: 'Active',
      joined: '2025-05-20',
    },
    {
      id: 70,
      name: 'Natalie Watson',
      email: 'natalie@example.com',
      initials: 'NW2',
      role: 'Admin',
      status: 'Active',
      joined: '2025-06-01',
    },
  ];

  get stats() {
    return [
      { label: 'Total Users', value: this.users.length, sub: 'All time' },
      {
        label: 'Active',
        value: this.users.filter((u) => u.status === 'Active').length,
        sub: 'Currently active',
      },
      {
        label: 'Pending',
        value: this.users.filter((u) => u.status === 'Pending').length,
        sub: 'Awaiting approval',
      },
      {
        label: 'Inactive',
        value: this.users.filter((u) => u.status === 'Inactive').length,
        sub: 'Inactive accounts',
      },
    ];
  }

  roleChartData = {
    labels: ['Admin', 'Editor', 'Viewer'],
    datasets: [
      { data: [5, 20, 45], backgroundColor: ['#0a0a0a', '#6b7280', '#d1d5db'], borderWidth: 0 },
    ],
  };

  statusChartData = {
    labels: ['Active', 'Inactive', 'Pending'],
    datasets: [
      { data: [52, 10, 8], backgroundColor: ['#22c55e', '#d1d5db', '#f59e0b'], borderWidth: 0 },
    ],
  };

  joinedChartData = {
    labels: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
    datasets: [
      {
        label: 'New Users',
        data: [2, 3, 4, 4, 5, 4, 4, 4, 4, 4, 4, 4],
        backgroundColor: '#0a0a0a',
        borderRadius: 4,
      },
    ],
  };

  doughnutOptions = {
    plugins: {
      legend: { position: 'bottom', labels: { font: { size: 11 }, padding: 16, boxWidth: 12 } },
    },
    cutout: '70%',
  };

  barOptions = {
    plugins: { legend: { display: false } },
    scales: {
      x: { grid: { display: false }, ticks: { font: { size: 11 } } },
      y: { grid: { color: 'rgba(0,0,0,0.05)' }, ticks: { font: { size: 11 }, stepSize: 5 } },
    },
  };
}
